<?php

namespace PrimeElementorAddons\Config;

use PrimeElementorAddons\Traits\Singleton;

if (!defined('ABSPATH')) {
    exit;
} // Exit if accessed directly

/**
 * Widget List Configuration
 *
 * Manages the list of available widgets, their configuration,
 * and registration status.
 *
 * @package PrimeElementorAddons
 * @since 1.0.0
 */

class WidgetList {

    use Singleton;

    private $widgets = [];

    public function __construct()
    {
        $this->init_widgets();
    }


    private function init_widgets()
    {
        $this->widgets = [
            'accordion' => [
                'slug' => 'accordion',
                'title' => 'Advanced Accordion',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/accordion.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedAccordion',
                'child' => 'false',
            ],
            'advanced-button' => [
                'slug' => 'advanced-button',
                'title' => 'Advanced Button',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-button.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedButton',
                'child' => 'false',
            ],
            'advanced-heading' => [
                'slug' => 'advanced-heading',
                'title' => 'Advanced Heading',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-heading.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedHeading',
                'child' => 'false',
            ],
            'back-to-top' => [
                'slug' => 'back-to-top',
                'title' => 'Back To Top',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/back-to-top.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'BackToTop',
                'child' => 'false',
            ],
            'advanced-image' => [
                'slug' => 'advanced-image',
                'title' => 'Advanced Image',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-image.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedImage',
                'child' => 'false',
            ],
            'advanced-navigation' => [
                'slug' => 'advanced-navigation',
                'title' => 'Advanced Menu',
                'package' => 'free',
                'category' => 'navigation',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-navigation.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedMenu',
                'child' => 'false',
            ],
            'advanced-paragraph' => [
                'slug' => 'advanced-paragraph',
                'title' => 'Advanced Paragraph',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-paragraph.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedParagraph',
                'child' => 'false',
            ],
            'advanced-search' => [
                'slug' => 'advanced-search',
                'title' => 'Advanced Search',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-search.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedSearch',
                'child' => 'false',
            ],
            'advanced-video' => [
                'slug' => 'advanced-video',
                'title' => 'Advanced Video',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-video.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedVideo',
                'child' => 'false',
            ],
            'animated-heading' => [
                'slug' => 'animated-heading',
                'title' => 'Animated Heading',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/animated-heading.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AnimatedHeading',
                'child' => 'false',
            ],
            'advanced-google-map' => [
                'slug' => 'advanced-google-map',
                'title' => 'Advanced Google Map',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/google-map.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedGoogleMaps',
                'child' => 'false',
            ],
            'advanced-off-canvas' => [
                'slug' => 'advanced-off-canvas',
                'title' => 'Advanced Off Canvas',
                'package' => 'pro',
                'category' => 'navigation',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-off-canvas.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedOffCanvas',
                'child' => 'false',
            ],
            'advanced-mega-menu' => [
                'slug' => 'advanced-mega-menu',
                'title' => 'Advanced Mega Menu',
                'package' => 'pro',
                'category' => 'navigation',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-mega-menu.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedMegaMenu',
                'child' => 'false',
            ],
            'advanced-model-popup' => [
                'slug' => 'advanced-model-popup',
                'title' => 'Advanced Model Popup',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-model-popup.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedModelPopup',
                'child' => 'false',
            ],
            'advanced-countdown' => [
                'slug' => 'advanced-countdown',
                'title' => 'Advanced CountDown',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/countdown.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedCountdown',
                'child' => 'false',
            ],
             'advanced-multi-cart' => [
                'slug' => 'advanced-multi-cart',
                'title' => 'Advanced Multi Chart',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/multi-chart.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedMultichart',
                'child' => 'false',
            ],
            'breadcrumb' => [
                'slug' => 'breadcrumb',
                'title' => 'Breadcrumb',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/breadcrumb.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'Breadcrumb',
                'child' => 'false',
            ],
            'business-hours' => [
                'slug' => 'business-hours',
                'title' => 'Business Hours',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/business-hours.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'BusinessHours',
                'child' => 'false',
            ],
            'call-to-action' => [
                'slug' => 'call-to-action',
                'title' => 'Call to Action',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/call-to-action.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'CallToAction',
                'child' => 'false',
            ],
            'contact-form-7' => [
                'slug' => 'contact-form-7',
                'title' => 'Contact Form 7',
                'package' => 'free',
                'category' => 'form',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/form.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ContactForm7',
                'child' => 'false',
            ],
            'countdown' => [
                'slug' => 'countdown',
                'title' => 'Countdown',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/countdown.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'CountDown',
                'child' => 'false',
            ],
            'counter-number' => [
                'slug' => 'counter-number',
                'title' => 'Counter Number',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/counter-number.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'Counter',
                'child' => 'false',
            ],
            'circle-menu' => [
                'slug' => 'circle-menu',
                'title' => 'Circle Menu',
                'package' => 'pro',
                'category' => 'navigation',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/circle-menu.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'CircleMenu',
                'child' => 'false',
            ],
            'code-snippet' => [
                'slug' => 'code-snippet',
                'title' => 'Code Snippet',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/code-snippet.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'CodeSnippet',
                'child' => 'false',
            ],
            'dual-button' => [
                'slug' => 'dual-button',
                'title' => 'Dual Button',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-button.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'DualButton',
                'child' => 'false',
            ],
            'content-table' => [
                'slug' => 'content-table',
                'title' => 'Content Table',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/content-table.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ContentTable',
                'child' => 'false',
            ],
            'features-list' => [
                'slug' => 'features-list',
                'title' => 'Features List',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/features-list.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'FeatureList',
                'child' => 'false',
            ],
            'flip-box' => [
                'slug' => 'flip-box',
                'title' => 'Flip Box',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/flip-box.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'FlipBox',
                'child' => 'false',
            ],
            'fluent-form' => [
                'slug' => 'fluent-form',
                'title' => 'Fluent Form',
                'package' => 'free',
                'category' => 'form',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/form.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'FluentForm',
                'child' => 'false',
            ],
            'horizontal-timeline' => [
                'slug' => 'horizontal-timeline',
                'title' => 'Horizontal Timeline',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/horizontal-timeline.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'HorizontalTimelines',
                'child' => 'false',
            ],
            'pie-chart' => [
                'slug' => 'pie-chart',
                'title' => 'Pie Chart',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/pie-chart.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PieChart',
                'child' => 'false',
            ],
            'icon-box' => [
                'slug' => 'icon-box',
                'title' => 'Icon Box',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/icon-box.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'IconBox',
                'child' => 'false',
            ],
            'image-gallery' => [
                'slug' => 'image-gallery',
                'title' => 'Image Gallery',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/image-gallery.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ImageGallery',
                'child' => 'false',
            ],
            'info-box' => [
                'slug' => 'info-box',
                'title' => 'Info Box',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/info-box.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'InfoBox',
                'child' => 'false',
            ],
            'image-hotspot' => [
                'slug' => 'image-hotspot',
                'title' => 'Image Hotspot',
                'package' => 'pro',
                'category' => 'media',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/image-hotspot.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ImageHotspot',
                'child' => 'false',
            ],
            'lottie-animation' => [
                'slug' => 'lottie-animation',
                'title' => 'Lottie Animation',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/lottie-animation.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'LottieAnimation',
                'child' => 'false',
            ],
            'multi-column-pricing-table' => [
                'slug' => 'multi-column-pricing-table',
                'title' => 'Multicolumn Pricing Table',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/pricing-table.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'MulticolumnPricingTable\MulticolumnPricingTable',
                'child' => 'false',
            ],
            'marquee-carousel' => [
                'slug' => 'marquee-carousel',
                'title' => 'Marquee Carousel',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/marquee-carousel.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'MarqueeCarousel',
                'child' => 'false',
            ],  
            'media-carousel' => [
                'slug' => 'media-carousel',
                'title' => 'Media Carousel',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/marquee-carousel.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'MediaCarousel',
                'child' => 'false',
            ],
            'post-grid' => [
                'slug' => 'post-grid',
                'title' => 'Post Grid',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-grid.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostGrid',
                'child' => 'false',
            ],
            'post-category' => [
                'slug' => 'post-category',
                'title' => 'Post Category',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-category.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostCategory',
                'child' => 'false',
            ],
            'product-grid' => [
                'slug' => 'product-grid',
                'title' => 'Product Grid',
                'package' => 'free',
                'category' => 'woocommerce',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/product-grid.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ProductGrid',
                'child' => 'false',
            ],
            'post-ticker' => [
                'slug' => 'post-ticker',
                'title' => 'Post Ticker',
                'package' => 'pro',
                'category' => 'post',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-ticker.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTicker',
                'child' => 'false',
            ],
            'post-timeline' => [
                'slug' => 'post-timeline',
                'title' => 'Post Timeline',
                'package' => 'pro',
                'category' => 'post',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-timeline.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTimeline',
                'child' => 'false',
            ],
            'pricing-table' => [
                'slug' => 'pricing-table',
                'title' => 'Pricing Table',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/pricing-table.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PricingTable',
                'child' => 'false',
            ],
            'progressbar' => [
                'slug' => 'progressbar',
                'title' => 'Progressbar',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/progressbar.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ProgressBar',
                'child' => 'false',
            ],
            'rive-animation' => [
                'slug' => 'rive-animation',
                'title' => 'Rive Animation',
                'package' => 'free',
                'category' => 'media',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/rive-animation.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'RiveAnimation',
                'child' => 'false',
            ],
            'slider' => [
                'slug' => 'slider',
                'title' => 'Advanced Slider',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-slider.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedSlider',
                'child' => 'false',
            ],
            'social-icons' => [
                'slug' => 'social-icons',
                'title' => 'Social Icons',
                'package' => 'free',
                'category' => 'social',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/social-icons.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'SocialIcons',
                'child' => 'false',
            ],
            'stacked-card' => [
                'slug' => 'stacked-card',
                'title' => 'Stacked Card',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/stacked-card.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'StackedCard',
                'child' => 'false',
            ],
            'tabs' => [
                'slug' => 'tabs',
                'title' => 'Advanced Tabs',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-tabs.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedTabs',
                'child' => 'false',
            ],
            'team-member' => [
                'slug' => 'team-member',
                'title' => 'Team Member',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/team-member.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'TeamMember',
                'child' => 'false',
            ],
            'testimonial' => [
                'slug' => 'testimonial',
                'title' => 'Testimonial',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/testimonial.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'Testimonial',
                'child' => 'false',
            ],
            'news-ticker' => [
                'slug' => 'news-ticker',
                'title' => 'News Ticker',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-ticker.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'NewsTicker',
                'child' => 'false',
            ],
            'woo-product-carousel' => [
                'slug' => 'woo-product-carousel',
                'title' => 'Woo Product Carousel',
                'package' => 'pro',
                'category' => 'woocommerce',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/marquee-carousel.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'WooProductCarousel',
                'child' => 'false',
            ],
            'advanced-switcher' => [
                'slug' => 'advanced-switcher',
                'title' => 'Advanced Switcher',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/advanced-switcher.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'AdvancedSwitcher',
                'child' => 'false',
            ],
            'image-comparison' => [
                'slug' => 'image-comparison',
                'title' => 'Image Comparison',
                'package' => 'pro',
                'category' => 'media',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/image-compare.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ImageComparison',
                'child' => 'false',
            ],
            'image-accordion' => [
                'slug' => 'image-accordion',
                'title' => 'Image Accordion',
                'package' => 'pro',
                'category' => 'media',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/accordion.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ImageAccordion',
                'child' => 'false',
            ],
            'page-progressbar' => [
                'slug' => 'page-progressbar',
                'title' => 'Page Progressbar',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/page-progressbar.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PageProgressBar',
                'child' => 'false',
            ],
            'post-carousel' => [
                'slug' => 'post-carousel',
                'title' => 'Post Carousel',
                'package' => 'pro',
                'category' => 'post',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-carousel.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostCarousel',
                'child' => 'false',
            ],
            'post-title' => [
                'slug' => 'post-title',
                'title' => 'Post Title',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-title.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostTitle',
                'child' => 'false',
            ],
            'post-content' => [
                'slug' => 'post-content',
                'title' => 'Post Content',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-content.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostContent',
                'child' => 'false',
            ],
            'post-featured-image' => [
                'slug' => 'post-featured-image',
                'title' => 'Post Featured Image',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-featured-image.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostFeaturedImage',
                'child' => 'false',
            ],
            'post-categories' => [
                'slug' => 'post-categories',
                'title' => 'Post Categories',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-categories.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostCategories',
                'child' => 'false',
            ],
            'post-share-icons' => [
                'slug' => 'post-share-icons',
                'title' => 'Post Share Icons',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-share-icons.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostShareIcons',
                'child' => 'false',
            ],
            'post-navigation' => [
                'slug' => 'post-navigation',
                'title' => 'Post Navigation',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-navigation.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostNavigation',
                'child' => 'false',
            ],
            'post-meta' => [
                'slug' => 'post-meta',
                'title' => 'Post Meta',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-meta.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostMeta',
                'child' => 'false',
            ],
            'post-author' => [
                'slug' => 'post-author',
                'title' => 'Post Author',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-author.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostAuthor',
                'child' => 'false',
            ],
            'post-comment' => [
                'slug' => 'post-comment',
                'title' => 'Post Comment',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-comment.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PostTemplate\PostComment',
                'child' => 'false',
            ],
            'price-menu' => [
                'slug' => 'price-menu',
                'title' => 'Price Menu',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/price-menu.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PriceMenu',
                'child' => 'false',
            ],
            'price-list' => [
                'slug' => 'price-list',
                'title' => 'Price List',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/price-list.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PriceList',
                'child' => 'false',
            ],
            'pdf-viewer' => [
                'slug' => 'pdf-viewer',
                'title' => 'PDF Viewer',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/pdf-viewer.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'PdfViewer',
                'child' => 'false',
            ],
            'archive-title' => [
                'slug' => 'archive-title',
                'title' => 'Archive Title',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-title.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ArchiveTemplate\ArchiveTitle',
                'child' => 'false',
            ],
            'archive-description' => [
                'slug' => 'archive-description',
                'title' => 'Archive Description',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/archive-description.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ArchiveTemplate\ArchiveDescription',
                'child' => 'false',
            ],
            'archive-post-grid' => [
                'slug' => 'archive-post-grid',
                'title' => 'Archive Post Grid',
                'package' => 'free',
                'category' => 'post',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-grid.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'ArchiveTemplate\ArchivePostGrid',
                'child' => 'false',
            ],
            'template' => [
                'slug' => 'template',
                'title' => 'Template',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/template-widget.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'Template',
                'child' => 'false',
            ],
            'table-of-contents' => [
                'slug' => 'table-of-contents',
                'title' => 'Table of Contents',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'freemium',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/table-of-contents.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'TableOfContents',
                'child' => 'false',
            ],
            'vertical-timeline' => [
                'slug' => 'vertical-timeline',
                'title' => 'Vertical Timeline',
                'package' => 'pro',
                'category' => 'content',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/post-timeline.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'VerticalTimeline',
                'child' => 'false',
            ],
            'site-title' => [
                'slug' => 'site-title',
                'title' => 'Site Title',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/site-title.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'SiteTitle',
                'child' => 'false',
            ],
            'site-tagline' => [
                'slug' => 'site-tagline',
                'title' => 'Site Tagline',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/site-tagline.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'SiteTagline',
                'child' => 'false',
            ],
            'site-logo' => [
                'slug' => 'site-logo',
                'title' => 'Site Logo',
                'package' => 'free',
                'category' => 'content',
                'badge' => 'free',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/site-logo.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'SiteLogo',
                'child' => 'false',
            ],
            'woo-mini-cart' => [
                'slug' => 'woo-mini-cart',
                'title' => 'Advanced Mini Cart',
                'package' => 'pro',
                'category' => 'woocommerce',
                'badge' => 'pro',
                'status' => 'true',
                'icon' => PEA_PLUGIN_URL . 'assets/icons/woo-mini-cart.svg',
                'doc' => 'https://wpmessiah.com/',
                'demo' => 'https://wpmessiah.com/',
                'complete' => 'true',
                'class' => 'WooMiniCart',
                'child' => 'false',
            ],
        ];
        $this->widgets = apply_filters('prime_elementor_addons_widgets_list', $this->widgets);
    }

    public function get_widgets()
    {
        return $this->widgets;
    }

    public function get_widget($slug)
    {
        return isset($this->widgets[$slug]) ? $this->widgets[$slug] : null;
    }

    public function get_default_widgets()
    {
        //now return init widgets
        return $this->widgets;
    }
}
